version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wemos_ergo_dev
    volumes:
      - wemos_ergo_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wemos-ergo-networks
volumes:
  wemos_ergo_data:
  
networks:
  wemos-ergo-networks:
    driver: bridge